//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("stocksModel", "FK4B9C6BC03F7C8B7F", "stocklist", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StockManager.stock), "stockdata", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StockManager.stockdata), true)]

#endregion

namespace StockManager
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class stocksEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new stocksEntities object using the connection string found in the 'stocksEntities' section of the application configuration file.
        /// </summary>
        public stocksEntities() : base("name=stocksEntities", "stocksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new stocksEntities object.
        /// </summary>
        public stocksEntities(string connectionString) : base(connectionString, "stocksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new stocksEntities object.
        /// </summary>
        public stocksEntities(EntityConnection connection) : base(connection, "stocksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<stockdata> stockdatas
        {
            get
            {
                if ((_stockdatas == null))
                {
                    _stockdatas = base.CreateObjectSet<stockdata>("stockdatas");
                }
                return _stockdatas;
            }
        }
        private ObjectSet<stockdata> _stockdatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<stock> stocks
        {
            get
            {
                if ((_stocks == null))
                {
                    _stocks = base.CreateObjectSet<stock>("stocks");
                }
                return _stocks;
            }
        }
        private ObjectSet<stock> _stocks;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the stockdatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostockdatas(stockdata stockdata)
        {
            base.AddObject("stockdatas", stockdata);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the stocks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostocks(stock stock)
        {
            base.AddObject("stocks", stock);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stocksModel", Name="stock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class stock : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new stock object.
        /// </summary>
        /// <param name="stock_id">Initial value of the stock_id property.</param>
        public static stock Createstock(global::System.Int32 stock_id)
        {
            stock stock = new stock();
            stock.stock_id = stock_id;
            return stock;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stock_id
        {
            get
            {
                return _stock_id;
            }
            set
            {
                if (_stock_id != value)
                {
                    Onstock_idChanging(value);
                    ReportPropertyChanging("stock_id");
                    _stock_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("stock_id");
                    Onstock_idChanged();
                }
            }
        }
        private global::System.Int32 _stock_id;
        partial void Onstock_idChanging(global::System.Int32 value);
        partial void Onstock_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ticker
        {
            get
            {
                return _ticker;
            }
            set
            {
                OntickerChanging(value);
                ReportPropertyChanging("ticker");
                _ticker = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ticker");
                OntickerChanged();
            }
        }
        private global::System.String _ticker;
        partial void OntickerChanging(global::System.String value);
        partial void OntickerChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("stocksModel", "FK4B9C6BC03F7C8B7F", "stockdata")]
        public EntityCollection<stockdata> stockdatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<stockdata>("stocksModel.FK4B9C6BC03F7C8B7F", "stockdata");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<stockdata>("stocksModel.FK4B9C6BC03F7C8B7F", "stockdata", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stocksModel", Name="stockdata")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class stockdata : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new stockdata object.
        /// </summary>
        /// <param name="stock_id">Initial value of the stock_id property.</param>
        /// <param name="history_ORDER">Initial value of the history_ORDER property.</param>
        public static stockdata Createstockdata(global::System.Int32 stock_id, global::System.Int32 history_ORDER)
        {
            stockdata stockdata = new stockdata();
            stockdata.stock_id = stock_id;
            stockdata.history_ORDER = history_ORDER;
            return stockdata;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stock_id
        {
            get
            {
                return _stock_id;
            }
            set
            {
                if (_stock_id != value)
                {
                    Onstock_idChanging(value);
                    ReportPropertyChanging("stock_id");
                    _stock_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("stock_id");
                    Onstock_idChanged();
                }
            }
        }
        private global::System.Int32 _stock_id;
        partial void Onstock_idChanging(global::System.Int32 value);
        partial void Onstock_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> adjClose
        {
            get
            {
                return _adjClose;
            }
            set
            {
                OnadjCloseChanging(value);
                ReportPropertyChanging("adjClose");
                _adjClose = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("adjClose");
                OnadjCloseChanged();
            }
        }
        private Nullable<global::System.Decimal> _adjClose;
        partial void OnadjCloseChanging(Nullable<global::System.Decimal> value);
        partial void OnadjCloseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> close
        {
            get
            {
                return _close;
            }
            set
            {
                OncloseChanging(value);
                ReportPropertyChanging("close");
                _close = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("close");
                OncloseChanged();
            }
        }
        private Nullable<global::System.Decimal> _close;
        partial void OncloseChanging(Nullable<global::System.Decimal> value);
        partial void OncloseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> high
        {
            get
            {
                return _high;
            }
            set
            {
                OnhighChanging(value);
                ReportPropertyChanging("high");
                _high = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("high");
                OnhighChanged();
            }
        }
        private Nullable<global::System.Decimal> _high;
        partial void OnhighChanging(Nullable<global::System.Decimal> value);
        partial void OnhighChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> low
        {
            get
            {
                return _low;
            }
            set
            {
                OnlowChanging(value);
                ReportPropertyChanging("low");
                _low = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("low");
                OnlowChanged();
            }
        }
        private Nullable<global::System.Decimal> _low;
        partial void OnlowChanging(Nullable<global::System.Decimal> value);
        partial void OnlowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> open
        {
            get
            {
                return _open;
            }
            set
            {
                OnopenChanging(value);
                ReportPropertyChanging("open");
                _open = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("open");
                OnopenChanged();
            }
        }
        private Nullable<global::System.Decimal> _open;
        partial void OnopenChanging(Nullable<global::System.Decimal> value);
        partial void OnopenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> volume
        {
            get
            {
                return _volume;
            }
            set
            {
                OnvolumeChanging(value);
                ReportPropertyChanging("volume");
                _volume = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("volume");
                OnvolumeChanged();
            }
        }
        private Nullable<global::System.Int64> _volume;
        partial void OnvolumeChanging(Nullable<global::System.Int64> value);
        partial void OnvolumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 history_ORDER
        {
            get
            {
                return _history_ORDER;
            }
            set
            {
                if (_history_ORDER != value)
                {
                    Onhistory_ORDERChanging(value);
                    ReportPropertyChanging("history_ORDER");
                    _history_ORDER = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("history_ORDER");
                    Onhistory_ORDERChanged();
                }
            }
        }
        private global::System.Int32 _history_ORDER;
        partial void Onhistory_ORDERChanging(global::System.Int32 value);
        partial void Onhistory_ORDERChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("stocksModel", "FK4B9C6BC03F7C8B7F", "stocklist")]
        public stock stock
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<stock>("stocksModel.FK4B9C6BC03F7C8B7F", "stocklist").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<stock>("stocksModel.FK4B9C6BC03F7C8B7F", "stocklist").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<stock> stockReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<stock>("stocksModel.FK4B9C6BC03F7C8B7F", "stocklist");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<stock>("stocksModel.FK4B9C6BC03F7C8B7F", "stocklist", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
